name: Build and Push Docker image (Patrick Testing)

on:
  workflow_dispatch:

  push:
    branches:
      - 'feat/celo'
env:
  REGISTRY: us-west1-docker.pkg.dev/devopsre/clabs-public-images
  CONTAINER: safe-config-service

jobs:
  Build-Push-Docker:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      id-token: write
      contents: read
      security-events: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Build the Docker image
        run: docker build -t ${{ env.CONTAINER }}:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.CONTAINER }}:${{ github.sha}}"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-results.sarif"
          security-checks: "vuln,config"
          timeout: 10m0s

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955'
        with:
          workload_identity_provider: 'projects/1094498259535/locations/global/workloadIdentityPools/gh-safe-config-service/providers/github-by-repos'
          service_account: 'safe-config-service-images@devopsre.iam.gserviceaccount.com'
          access_token_lifetime: '50m'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb'

      - name: 'Configure docker for gcloud auth'
        run: 'gcloud auth configure-docker us-west1-docker.pkg.dev'

      - id: docker-push-latest-patrick-test
        name: Build Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          platforms: linux/amd64
          push: true
          context: .
          tags: |
             ${{ env.REGISTRY }}/${{ env.CONTAINER }}:latest-patrick-test
             ${{ env.REGISTRY }}/${{ env.CONTAINER }}:${{ github.sha }}
