name: Lint and Test Charts

on: 
  workflow_dispatch:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.2

      - name: Build dependencies
        run: |
          helm dep update ./helm-chart

      - name: Lint
        run: |
          helm lint ./helm-chart --strict

      - name: Template
        run: |
          helm template ./helm-chart -f helm-chart/values-test.yaml

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Check k8s objects conform with API 
        run: helm template ./helm-chart -f helm-chart/values-test.yaml --validate
